#include "vepch.h"
#include "ShaderGenerator.h"
#include "MaterialNodes.h"

#include "Core/Log.h"

namespace ve {

	static const char* VERTEX_SHADER_TEMPLATE = R"(
#version 460 core
// Auto-generated by Vosta Material Compiler
layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec3 a_Normal;
layout(location = 3) in vec3 a_Tangent;

layout(location = 0) out vec3 v_WorldPos;
layout(location = 1) out vec2 v_TexCoord;
layout(location = 2) out mat3 v_TBN;

uniform mat4 u_Model;
uniform mat4 u_ViewProj;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_WorldPos = worldPos.xyz;
    v_TexCoord = a_TexCoord;

    vec3 T = normalize(mat3(u_Model) * a_Tangent);
    vec3 N = normalize(mat3(u_Model) * a_Normal);
    T = normalize(T - dot(T, N) * N);
    vec3 B = cross(N, T);
    v_TBN = mat3(T, B, N);

    gl_Position = u_ViewProj * worldPos;
}
)";

	static const char* FRAGMENT_HEADER = R"(
#version 460 core
layout(location = 0) in vec3 v_WorldPos;
layout(location = 1) in vec2 v_TexCoord;
layout(location = 2) in mat3 v_TBN;

layout(location = 0) out vec4 Frag0_Albedo;
layout(location = 1) out vec4 Frag1_Normal;
layout(location = 2) out vec4 Frag2_Material;
layout(location = 3) out vec4 Frag3_Emissive;

uniform float u_Time;

)";

	// Insert a GLSL type conversion when source and destination pin types differ,
	// so that e.g. a Float4 texture output can connect to a Float3 BaseColor input.
	static std::string convertType(const std::string& var, PinType from, PinType to) {
		if (from == to) return var;

		// Narrowing (vec4/vec3/vec2 → smaller)
		if (from == PinType::Float4 && to == PinType::Float3) return var + ".rgb";
		if (from == PinType::Float4 && to == PinType::Float2) return var + ".rg";
		if (from == PinType::Float4 && to == PinType::Float)  return var + ".r";

		if (from == PinType::Float3 && to == PinType::Float2) return var + ".rg";
		if (from == PinType::Float3 && to == PinType::Float)  return var + ".r";

		if (from == PinType::Float2 && to == PinType::Float)  return var + ".x";

		// Widening (float/vec2/vec3 → larger)
		if (from == PinType::Float  && to == PinType::Float2) return "vec2(" + var + ")";
		if (from == PinType::Float  && to == PinType::Float3) return "vec3(" + var + ")";
		if (from == PinType::Float  && to == PinType::Float4) return "vec4(" + var + ")";

		if (from == PinType::Float2 && to == PinType::Float3) return "vec3(" + var + ", 0.0)";
		if (from == PinType::Float2 && to == PinType::Float4) return "vec4(" + var + ", 0.0, 1.0)";

		if (from == PinType::Float3 && to == PinType::Float4) return "vec4(" + var + ", 1.0)";

		return var; // Sampler2D or unknown — pass through unchanged
	}

	void ShaderGenerator::compile(const MaterialGraph& graph, std::string& outVertSrc, std::string& outFragSrc){

		MaterialNode* outputNode = nullptr;
		for (const auto& node : graph.nodes) {
			if (auto* o = dynamic_cast<MaterialOutputNode*>(node.get())) {

				if (outputNode) {
					//TODO: Log multiple output node error
					return;
				}
				outputNode = o;
			}
		}

		if (!outputNode) {
			VE_CORE_ERROR_PRINT("No MaterialOutput node in graph");
			return;
		}

		auto sorted = graph.topologicalSort();
		if (sorted.empty()) return;

		ShaderGenContext ctx;
		std::unordered_map<uint32_t, std::vector<std::string>> varCache;

		int texSlot = 0;
		for (auto& node : sorted) {
			if (auto* tex = dynamic_cast<TextureSamplerNode*>(node.get())) {
				tex->samplerName = "u_MatTex_" + std::to_string(texSlot);
				ctx.samplers << tex->generateSamplerDeclaration(texSlot);
				texSlot++;
			}
		}

		for (auto& node : sorted) {
			if (node.get() == outputNode) continue;
			generateNodeCode(node, graph, ctx, varCache);
		}

		std::vector<std::string> outputInputs;
		for (size_t i = 0; i < outputNode->m_inputPins.size(); ++i) {
			const GraphLink* found = nullptr;
			for (auto& link : graph.links) {
				if (link.endPin.id == outputNode->id && link.endPin.pinIndex == i) {
					found = &link;
					break;
				}
			}
			if (found) {
				auto& srcVars = varCache[found->startPin.id];
				std::string varName = srcVars[found->startPin.pinIndex];

				// Apply type conversion if source and destination types differ.
				GraphNode* srcNode = graph.findNode(found->startPin.id);
				if (srcNode) {
					uint32_t realOutIdx = found->startPin.pinIndex - (uint32_t)srcNode->m_inputPins.size();
					if (realOutIdx < srcNode->m_outputPins.size()) {
						PinType srcType = srcNode->m_outputPins[realOutIdx].type;
						PinType dstType = outputNode->m_inputPins[i].type;
						varName = convertType(varName, srcType, dstType);
					}
				}
				outputInputs.push_back(varName);
			}
			else {
				outputInputs.push_back("DEFAULT_" + std::to_string(i));
			}
		}

		std::string outputCode = outputNode->generateCode(outputInputs, {});
		ctx.mainFunction << "    " << outputCode << "\n";

		outVertSrc = VERTEX_SHADER_TEMPLATE;
		outFragSrc = std::string(FRAGMENT_HEADER)
			+ ctx.samplers.str()
			+ ctx.uniforms.str()
			+ ctx.functions.str()
			+ "\nvoid main() {\n"
			+ ctx.mainFunction.str()
			+ "}\n";


	}
	void ShaderGenerator::generateNodeCode(Ref<GraphNode> node, const MaterialGraph& graph, ShaderGenContext& ctx, std::unordered_map<uint32_t, std::vector<std::string>>& varCache){

		std::vector<std::string> inputVars;
		for (size_t i = 0; i < node->m_inputPins.size(); i++) {

			const GraphLink* foundLink = nullptr;
			for (auto& link : graph.links) {
				if (link.endPin.id == node->id && link.endPin.pinIndex == i) {
					foundLink = &link;
					break;
				}
			}

			if (foundLink) {
				auto& inputVarNames = varCache[foundLink->startPin.id];
				std::string varName = inputVarNames[foundLink->startPin.pinIndex];

				// Apply type conversion when source and destination pin types differ.
				GraphNode* srcNode = graph.findNode(foundLink->startPin.id);
				if (srcNode) {
					uint32_t realOutIdx = foundLink->startPin.pinIndex - (uint32_t)srcNode->m_inputPins.size();
					if (realOutIdx < srcNode->m_outputPins.size()) {
						PinType srcType = srcNode->m_outputPins[realOutIdx].type;
						PinType dstType = node->m_inputPins[i].type;
						varName = convertType(varName, srcType, dstType);
					}
				}
				inputVars.push_back(varName);

			}
			else {
				// A node may supply a meaningful default for an optional pin
				// (mesh UVs, the engine clock); otherwise it is the type's zero.
				std::string def = node->inputDefaultExpr(i);
				inputVars.push_back(def.empty() ? getDefaultValue(node->m_inputPins[i].type) : def);
			}
		}

		std::vector<std::string> outputVars;
		for (auto& output : node->m_outputPins) {
			outputVars.push_back(ctx.allocVar());
		}

		auto* materialNode = dynamic_cast<MaterialNode*>(node.get());
		std::string code = materialNode ? materialNode->generateCode(inputVars,outputVars) : std::string();
		ctx.mainFunction << " " << code << "\n";

		// Store output vars indexed by actual pinIndex so lookups by PinId work correctly.
		// Pin indices are offset by input count (see MaterialGraph::assignPinIds).
		auto& cacheEntry = varCache[node->id];
		if (!node->m_outputPins.empty()) {
			uint32_t maxIdx = node->m_outputPins.back().id.pinIndex;
			cacheEntry.resize(maxIdx + 1);
			for (size_t i = 0; i < node->m_outputPins.size(); ++i) {
				cacheEntry[node->m_outputPins[i].id.pinIndex] = outputVars[i];
			}
		}
	}


}
